### PR TITLE
adapt open_visa()

### PR DESCRIPTION
**Pull request by macjohnny**
adapt for pyVisa > 1.5

### CODE REVIEW

**Comment by scasagrande** [comment]
Should we perhaps be checking for which version of pyVisa is installed for backwards compatibility?

**Comment by macjohnny** [comment]
good idea. will you do this?

**Comment by scasagrande** [comment]
It should be as simple as just putting a check around the lines you updated. If there a `visa.__version__` or something that we can check?

**Comment by macjohnny** [comment]
@scasagrande now it should also be backwards compatible

**Comment by scasagrande** [comment]
Awesome! Thank you very much for fixing this :D

**Pull request merged**
