### PR TITLE
Update srsdg645.py

### PR DESCRIPTION
**Pull request by trappitsch**
Added capabilities to SRS DG645 instrument:
Added the capability to set the level offset for each output. Used the exact same formalism as in level_amplitude subroutine.

### CODE REVIEW

**Comment by scasagrande** [comment]
So sorry!! I had forgotten to move my 2FA to my new phone and my laptop web session timed out haha.

If we can just get a quick test added to `instruments/tests/test_srs/test_srsdg645.py` that'll be perfect for this. That way then I can update things to use the property factories in the future.

**Comment by trappitsch** [comment]
Sorry, I was on vacation, but back now. I added the quick test case, as well as I understood it from the documentation. Let me know if I got it completely wrong or if it fits with what you wanted, I'm fairly new to this :)

Thanks!

**Comment by trappitsch** [comment]
@scasagrande: I'm not fully clear why the checks have failed. I probably don't understand all that well on how these are done. Any hints / ideas would be very much appreciated. Thanks!

**Comment by scasagrande** [comment]
Your tests look good to me! The CI failure isn't your fault. It looks like one of my dependencies was updated upstream and is now having issues. I'll have to fix that then I can merge in your work :)

**Comment by trappitsch** [comment]
Great, thanks for checking. I'll leave it in your hands then. Let me know if I can do anything. I'm planning on implementing more controls on this specific DG in the future, so more to come hopefully soon.

**Comment by scasagrande** [comment]
I finally got off my butt and fixed the build! I'm going to go ahead and merge your work. Thanks for the submission :)

**Pull request merged**
