### PR TITLE
Tests and typo fix for Generic SCPI Instruments

### PR DESCRIPTION
**Pull request by trappitsch**
- All three instruments now with full coverage
- Added tests to SCPI Function Generator
- Added tests to SCPI Multimeter
- Created tests for SCPI Instrument
- Corrected a typo / copy paste error: Contrast error message returned
  description for brightness instead of contrast.

### CODE REVIEW

**Comment by trappitsch** [comment]
Hmmm, `tox -e pylint` passed w/o any issues on my system. Also, travis seems to report an error in an untouched file:

```
instruments/tests/test_base_instrument.py:144:18: E1120: No value for argument 'device' in constructor call (no-value-for-parameter)

instruments/tests/test_base_instrument.py:150:19: E1120: No value for argument 'device' in constructor call (no-value-for-parameter)
instruments/tests/test_base_instrument.py:192:22: E1120: No value for argument 'device' in constructor call (no-value-for-parameter)
instruments/tests/test_base_instrument.py:198:23: E1120: No value for argument 'device' in constructor call (no-value-for-parameter)
```

Ideas?

**Comment by scasagrande** [comment]
Can you try `tox -re pylint` to re-create to see if its a dep issue

**Comment by trappitsch** [comment]
Good catch, now i get it on my machine as well. Getting the same issue on the main branch too (even w/ Galvant), but that one passed before the last merge, no?
Weird thing is, I also get 5 failed tests local for the numpy tests, e.g., `py39-numpy` errs out in the following way (on my branch and on my main branch)
```
FAILED instruments/tests/test_base_instrument.py::test_instrument_open_serial_by_usb_ids_multiple_matches - TypeError: __init__() missing 1 required positional ...
FAILED instruments/tests/test_base_instrument.py::test_instrument_open_serial_by_usb_ids_and_serial_number - TypeError: __init__() missing 1 required positional...
FAILED instruments/tests/test_base_instrument.py::test_instrument_open_serial_by_usb_ids - TypeError: __init__() missing 1 required positional argument: 'device'
FAILED instruments/tests/test_base_instrument.py::test_instrument_open_serial_by_usb_ids_incorrect_serial_num - TypeError: __init__() missing 1 required positio...
FAILED instruments/tests/test_base_instrument.py::test_instrument_open_serial_by_usb_ids_cant_find - TypeError: __init__() missing 1 required positional argumen...
```

**Comment by scasagrande** [comment]
Hmm, I see pyserial updated to 3.5, maybe that's related

**Comment by scasagrande** [comment]
Confirmed, tests pass with 3.4

**Comment by trappitsch** [comment]
Quite the find! Confirmed here, all passes w/ pyserial==3.4. Should figure out what changed here, don't see anything obvious from the changelog...

One thing I still don't understand: Just running

```console
pytest --cov=instruments instruments/tests
```

Passes all tests w/o failures...

**Comment by scasagrande** [comment]
Well, what version of pyserial do you have installed in your env?

**Comment by scasagrande** [comment]
Go ahead and refresh your branch and it should pass now

**Comment by trappitsch** [comment]
> Well, what version of pyserial do you have installed in your env?

Maybe I should go to bed... :smile: 

> Go ahead and refresh your branch and it should pass now

Running tox quick to make sure it all passes, but looking good so far. Thanks for the quick fix!

**Comment by trappitsch** [comment]
let's try again :)

**Comment by scasagrande** [comment]
lgtm!!

**Pull request merged**
